### 可调用测试
GET localhost:8000/api/hello-world

### 删除用户测试
DELETE localhost:8000/api/user/

{
  "username": "sindwerra"
}

### 创建用户测试
POST localhost:8000/api/user/

{
  "username": "sindwerra",
  "password": "102102102a"
}

### 获取角色测试
POST localhost:8000/api/role/list/

{
  "token": "HSBC-sindwerra-2023-08-31 10:46:18.067164"
}

### 检查角色测试
POST localhost:8000/api/role/check/

{
  "token": "HSBC-sindwerra-2023-08-31 10:46:18.067164",
  "role": "demon hunter"
}

### 创建角色测试
POST localhost:8000/api/role/

{
  "role_name": "demon hunter"
}

### 删除角色测试
DELETE localhost:8000/api/role/

{
  "role_name": "demon hunter"
}

### 用户绑定角色测试
POST localhost:8000/api/role/assign/

{
  "role": "demon hunter",
  "user": "sindwerra"
}

### 认证测试
POST localhost:8000/api/authenticate/

{
  "username": "sindwerra",
  "password": "102102102a"
}

### TOKEN失效测试
POST localhost:8000/api/invalidate/

{
  "token": "4158112244629831554"
}
